name: Release

concurrency: ci-${{ github.ref }}

on:
  workflow_dispatch:
  
  push:
    branches: [ main, develop ] # Default release branch
    paths-ignore:
      - '.github/**'
      - 'docs/**'

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  call-workflow-nuget-release:
    uses: Digitalroot-Valheim/.github/.github/workflows/nuget.release.yml@main
    secrets:
      aws-access-key-id: ${{ secrets.NUGET_S3_REPO_KEY_ID }}
      aws-secret-access-key: ${{ secrets.NUGET_S3_REPO_KEY_SECRET }}
      nuget-org-key: ${{ secrets.NUGET_ORG_PAT }}
    with:
      sln-file-name: Digitalroot.ModUploader
      proj-file-name: Digitalroot.ModUploader
      #skip-unit-tests: true
      nuget-gh-upload: true
      nuget-s3-upload: true
      nuget-org-upload: true
      is-nuget-package: true
